Several updates to doc and remove old files.
- Update old Ubuntu 20.04 and 22.04 references to Ubuntu 24.04.
- Remove outdated fastsurfer.yml conda environment file.
- Fix outdated/error-prone uv instructions that give errors on updating.
- Standardize documentation style of examples and usage fences.
  - document standardized format in doc/CONVENTIONS.md.
  - apply standardized placeholders, file names, paths, call signatures, etc.
  - also make argparse and shell script inline documentation consistent.
  - consistent use and explanation of `--no-mount home,cwd`
  - added replacement of {{ CUDA_VERSION }} {{ CUDA_STRING }}  and {{ FASTSURFER_VERSION }}, uses current versions on stable and last release on dev builds.
  - added a banner on top of commands that use replacements, slightly different texts
  - lots of doc consistency changes
  - some minor doc-relevant bugfixes
  - in places pre-empty a version update of pytorch (but keeps both for now)
  - bash fences and text fences have different meaning, bash => copy paste to your terminal, text => this is the pattern/usage, copy-paste must replace placeholders
- fixed some default values in scripts, in particular generate_hdf5.py
- exclude all .gitignored files from codespell checks

diff --git a/tools/Docker/Dockerfile b/tools/Docker/Dockerfile
--- a/tools/Docker/Dockerfile
+++ b/tools/Docker/Dockerfile
@@ -165,6 +165,8 @@ source /venv/bin/activate
 # uv pip sync only installs "exactly" the packages in the lockfile, but does not resolve dependencies
 # therefore, we first compile the environment to resolve dependencies, and then sync to install both directly and
 # indirectly required packages
+# pipefail: fail the build if uv pip compile fails, uv pip sync succeeds on the resulting empty input
+set -o pipefail
 if [[ "$PINNED_REQUIREMENTS" == "true" ]]; then
     uv pip compile --torch-backend=${DEVICE} /install/requirements.txt | uv pip sync --torch-backend=${DEVICE} -
 else
